apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-creds
  labels:
    {{- include "mailSender.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.mailSender.smtpUser | b64enc }}
  password: {{ .Values.mailSender.smtpPassword | b64enc }}
