apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitea-drone.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gitea-drone.name" . }}
    helm.sh/chart: {{ include "gitea-drone.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitea-drone.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gitea-drone.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_healthz
              port: http
          readinessProbe:
            httpGet:
              path: /_healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envs:
            - name: DRONE_URL
              value: {{ .Values.giteadrone.drone_url }}
            - name: DRONE_TOKEN
              value: {{ .Values.giteadrone.drone_token }}
          {{- with .Values.extraVolumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnvs }}
          volumeMounts:
          {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
