apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gitea.fullname" . }}
  labels:
    app: {{ template "gitea.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ default "gitea" .Values.service.nameOverride }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "gitea.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "gitea.fullname" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/{{ template "gitea.fullname" . }}-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 3000
            - containerPort: 22
            - containerPort: 33
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          resources:
          {{- with .Values.resources }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
          - name: data
            mountPath: /data
          - name: config
            mountPath: /data/gitea/conf/app.ini
            subPath: app.ini
          {{- with .Values.gitea.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "gitea.fullname" . }}-config
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitea.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
      {{- with .Values.gitea.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
