{{- if .Values.service.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $serviceName := default "gitea" .Values.service.nameOverride -}}
{{- $httpPort := .Values.service.http.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "gitea.fullname" . }}
  labels:
    app: {{ template "gitea.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ default "gitea" .Values.service.nameOverride }}
  annotations:
    {{- range $key, $value := .Values.service.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.service.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" $releaseName $serviceName | trunc 63 | trimSuffix "-" }}-http
                port:
                  number: {{ $httpPort }}
    {{- end -}}
{{- if .Values.service.ingress.tls }}
  tls:
{{ toYaml .Values.service.ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}
