{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.metrics.service.annotations }}
  annotations:
{{ toYaml .Values.metrics.service.annotations | indent 4 }}
{{- end }}
  labels:
{{- if .Values.metrics.service.labels }}
{{ toYaml .Values.metrics.service.labels | indent 4 }}
{{- end }}
    app: {{ template "nginx-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nginx-ingress.fullname" . }}-metrics
spec:
{{- if not .Values.metrics.service.omitClusterIP }}
  clusterIP: "{{ .Values.metrics.service.clusterIP }}"
{{- end }}
{{- if .Values.metrics.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.metrics.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.metrics.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.metrics.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.metrics.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.metrics.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
  selector:
    app: {{ template "nginx-ingress.name" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}
  type: "{{ .Values.metrics.service.type }}"
{{- end }}
