apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parse.mongodb.secretName" . }}
  labels: {{ include "parse.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootPassword: {{ .Values.mongodb.rootPassword }}