{{- if .Values.ingress.server.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ include "parse.fullname" . }}-server"
  labels: {{ include "parse.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.server.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.server.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.ingress.server.hosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            backend:
              serviceName: {{ include "parse.fullname" $ }}
              servicePort: server-http
    {{- end }}
  tls:
    {{- range .Values.ingress.server.hosts }}
    {{- if .tls }}
    - hosts:
    {{- if .tlsHosts }}
    {{- range $host := .tlsHosts }}
      - {{ $host }}
    {{- end }}
    {{- else }}
      - {{ .name }}
    {{- end }}
      secretName: {{ .tlsSecret }}
    {{- end }}
    {{- end }}
{{- end }}
