apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.credentials.secret" . }}
  labels:
    {{- include "parse-server.labels" . | nindent 4 }}
data:
  MONGODB_USER: {{ .Values.server.mongodb.user | b64enc | quote }}
  MONGODB_PASSWORD: {{ .Values.server.mongodb.password | b64enc | quote }}
